# Generated by Django 3.0.8 on 2020-07-26 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 11, 31, 58, 326668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 8, 36, 58, 334209, tzinfo=utc)),
        ),
    ]
