# Generated by Django 3.0.6 on 2020-06-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='agent_rate',
            field=models.FloatField(blank=True, default=0.2),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='call_contact',
            field=models.CharField(blank=True, default='08012345678', max_length=13),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='customer_rate',
            field=models.FloatField(blank=True, default=0.15),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email_contact',
            field=models.EmailField(blank=True, default='amisatechnologies@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='minimum_airtime',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='minimum_data',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='minimum_withdrawal',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='servies_notice',
            field=models.TextField(blank=True, default='Note is here'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_setting',
            field=models.CharField(blank=True, default='Setting_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp_contact',
            field=models.CharField(blank=True, default='08012345678', max_length=13),
        ),
    ]
