# Generated by Django 3.0.6 on 2020-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200610_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='agent_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='call_contact',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='customer_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='minimum_airtime',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='minimum_data',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='minimum_withdrawal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='servies_notice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp_contact',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
