# Generated by Django 3.0.8 on 2020-07-27 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200726_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 10, 31, 15, 329865, tzinfo=utc)),
        ),
    ]
