# Generated by Django 3.0.8 on 2020-07-24 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200724_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 39, 51, 16745, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 14, 44, 51, 24029, tzinfo=utc)),
        ),
    ]
