# Generated by Django 3.0.6 on 2020-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200604_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
