# Generated by Django 3.0.6 on 2020-06-11 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200611_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
