# Generated by Django 3.0.6 on 2020-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200604_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='CodeSlip',
        ),
    ]
