# Generated by Django 3.0.6 on 2020-06-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='how_to',
            field=models.TextField(blank=True),
        ),
    ]
