# Generated by Django 3.0.6 on 2020-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200606_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codegroup',
            name='code_group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
