# Generated by Django 3.0.8 on 2020-07-16 22:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0007_auto_20200705_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 0, 4, 25, 10)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 22, 9, 25, 10)),
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
