# Generated by Django 3.0.8 on 2020-07-18 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200716_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolution',
            options={'verbose_name': 'Resolution', 'verbose_name_plural': 'Resolutions'},
        ),
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 13, 30, 55, 10)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 10, 35, 55, 10)),
        ),
    ]
