# Generated by Django 3.0.8 on 2020-07-24 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200723_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 12, 41, 5, 200681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 9, 46, 5, 208642, tzinfo=utc)),
        ),
    ]
